name: Lint PR for app_theme.json

on:
  pull_request:

jobs:
  lint-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Find app_theme.json
        id: find_file
        run: |
          app_theme_file=$(git ls-files | grep "app_theme.json" || true)
          echo "app_theme_file=$app_theme_file" >> $GITHUB_ENV

      - name: Check for changes in app_theme.json
        id: check_changes
        run: |
          if [ -n "$app_theme_file" ] && git diff --name-only origin/main...HEAD | grep -q "$app_theme_file"; then
            echo "app_theme.json has changes."
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "No changes in app_theme.json."
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Check for '#' character in app_theme.json
        if: env.changed == 'true'
        run: |
          filtered_content=$(jq 'del(.globalColorTheme, .gradients, .elevation, .igniteTheme)' "$app_theme_file")
          
          if echo "$filtered_content" | grep -q "#"; then
            echo "Hash (#) character found in app_theme.json."
            exit 1
          else
            echo "No hash (#) character found in app_theme.json."
          fi
        shell: bash
