name: Lint PR for app_theme.json

on:
  pull_request:

jobs:
  lint-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Find app_theme.json
        id: find_file
        run: |
          app_theme_file=$(find . -name "app_theme.json" || true)
          if [ -z "$app_theme_file" ]; then
            echo "app_theme.json not found."
            exit 0
          fi
          echo "Found app_theme.json at $app_theme_file"
          echo "::set-output name=app_theme_file::$app_theme_file"

      - name: Check for '#' character in app_theme.json
        run: |
          filtered_content=$(jq 'del(.globalColorTheme, .gradients, .elevation, .igniteTheme)' "${{ steps.find_file.outputs.app_theme_file }}")
          
          if echo "$filtered_content" | grep -q "#"; then
            echo "Hash (#) character found in app_theme.json."
            exit 1
          else
            echo "No hash (#) character found in app_theme.json."
          fi
        shell: bash
